### ISSUE TITLE
FullCrud ignores change on Auth Template field when template = default

### ISSUE THREAD

**Issue by igorsantos07** [schmunk42/gii-template-collection#15]
I'm probably going to fix that soon and send a PR, this is just a reminder so I don't forget :P

**Comment by schmunk42** [comment]
Just a question: Have you tried the slim template?

**Comment by igorsantos07** [comment]
Yes, it works. I was just trying to understand what's the difference
between them - this should appear in the generator page, too.

**Comment by motin** [comment]
Fixed by https://github.com/schmunk42/gii-template-collection/commit/a5077f60c1bb5bbad921848cadee76cf21d0fb47
