### ISSUE TITLE
Clarify branch usage

### ISSUE THREAD

**Issue by motin** [schmunk42/gii-template-collection#42]
Right now, there is "release" branch which has the latest released and unreleased code, "development" branch with a bit older code and a new merge and "master" with really old code. 

I suggest we use https://github.com/nvie/gitflow for managing development, feature and release-branches.

**Comment by schmunk42** [comment]
Yeah, sorry for that.
I was not able to merge `back-to-the-roots` back into master.

Feel free to make `master` contain the latest code again. We could drop `development` then.

**Comment by motin** [comment]
Done
