### ISSUE TITLE
PHP 5.4 requirement

### ISSUE THREAD

**Issue by schmunk42** [schmunk42/gii-template-collection#43]
https://github.com/schmunk42/gii-template-collection/blob/development/composer.json#L16

@motin Do we have to require PHP 5.4?
Topic: Bobsled Style "<?= ?>"

**Comment by motin** [comment]
Don't see why we need 5.4 - do you know any code requiring it?

**Comment by schmunk42** [comment]
I looked it up again :)

But we need to require short_open_tags on
http://www.php.net/manual/en/ini.core.php#ini.short-open-tag

**Comment by schmunk42** [comment]
added to README
